[project]
name = "vectara-mcp"
version = "0.1.0"
description = "Vectara MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "uvicorn>=0.34.0",
    "vectara>=0.2.44",
]
